# Load base objects
require 'merlot/page_objects/base/default_locator_strategy'
require 'merlot/page_objects/base/element'
require 'merlot/page_objects/base/locator'

# Load basic page objects
require 'merlot/page_objects/button'
require 'merlot/page_objects/checkbox'
require 'merlot/page_objects/drop_down'
require 'merlot/page_objects/form'
require 'merlot/page_objects/image'
require 'merlot/page_objects/label'
require 'merlot/page_objects/link'
require 'merlot/page_objects/list_box'
require 'merlot/page_objects/node'
require 'merlot/page_objects/panel'
require 'merlot/page_objects/radio_button'
require 'merlot/page_objects/tab'
require 'merlot/page_objects/table'
require 'merlot/page_objects/text_box'
require 'merlot/page_objects/tooltip'
require 'merlot/page_objects/tree'

# Load AJAX page objects
require 'merlot/page_objects/ajax/button_AJAX'
require 'merlot/page_objects/ajax/checkbox_AJAX'
require 'merlot/page_objects/ajax/drop_down_AJAX'
require 'merlot/page_objects/ajax/label_AJAX'
require 'merlot/page_objects/ajax/progress_spinner_AJAX'
require 'merlot/page_objects/ajax/radio_button_AJAX'
require 'merlot/page_objects/ajax/text_box_AJAX'