source: "html/demos"
destination: "_site/demos"
baseurl: "http://demo.canon.rackspace.com"
canonurl: "http://ci.canon.rackspace.com/view/Canon/job/canon-screenshot/lastSuccessfulBuild/artifact/dist/"
