#!/usr/bin/env bash

set -e

log () {
  echo -e "\e[1m==> $@\e[0m"
}

error () {
  echo -e "\e[31;1m$@\e[0m"
}

success () {
  echo -e "\e[32;1m$@\e[0m"
}

warn () {
  echo -e "\e[33;1m$@\e[0m"
}

info () {
  echo -e "\e[36;1m$@\e[0m"
}

show_welcome_message () {
  echo ""
  info "Welcome to Canon!"
  echo ""

  cat <<-MESSAGE
Before you get started contributing to Canon, let's make sure that your
development environment has all the necessary dependencies. This script will:

  - Check for RVM or rbenv
  - Check for Ruby 2.x.x
  - Check for Node 0.6.0 or higher
  - Check for PhantomJS 1.7.0 or higher
  - Install Grunt
  - Install Bundler
  - Install Ruby dependencies
  - Install Node dependencies
  - Install Bower dependencies
  - Install Rackspace CLI

Press ENTER to continue.
MESSAGE

  read
}

check_version_manager () {
  log "Checking for Ruby version manager..."

  if [[ -z "$(command -v rvm)" && -z "$(command -v rbenv)" && -z "$(command -v chruby)" ]]; then
    warn "\nYou don't have a Ruby version manager installed. Proceed with caution.\n"
  fi
}

check_ruby_version () {
  log "Checking Ruby version..."

  version="$(ruby --version)"

  if ! [[ "$version" =~ "ruby 2" || "$version" =~ "ruby 1.9" ]]; then
    error "\nCanon required Ruby 2.x.x. Please update Ruby and try again.\n"
    exit 1
  fi
}

check_node_version () {
  log "Checking Node version..."

  version="$(node --version)"

  #if ! [[ "$version" =~ "v2" || "$version" =~ "v0.10" ]]; then
    #error "\nCanon requires Node 0.10.0 (or higher) or iojs 2.0.0 (or higher). Please update Node and try again.\n"
    #exit 1
  #fi

}

install_grunt () {
  log "Installing Grunt..."
  npm install -g bower grunt-cli
}

install_bundler () {
  log "Installing Bundler..."
  gem install bundler
}

install_gems () {
  log "Installing Ruby gems..."
  bundle install
}

install_npm_packages () {
  log "Installing NPM packages..."
  npm install
}

install_bower_components () {
  log "Installing Bower components..."
  node_modules/.bin/bower install
}

install_rack () {
  log "Installing Rackspace CLI..."

  echo $PATH
  mkdir -p $HOME/.bin
  curl -SL -o $HOME/.bin/rack https://ec4a542dbf90c03b9f75-b342aba65414ad802720b41e8159cf45.ssl.cf5.rackcdn.com/1.0.0-beta.1/Linux/amd64/rack
  chmod +x $HOME/.bin/rack
}

install_aws_cli () {
  log "Installing AWS CLI..."
  pip install --user awscli
}


if [[ $CI != true ]]; then
  show_welcome_message
fi

check_version_manager
check_ruby_version
check_node_version

install_grunt
install_bundler
install_gems
install_npm_packages
install_bower_components
install_rack
install_aws_cli

success "\nCanon setup completed successfully!\n"
