#!/usr/bin/env ruby

require 'rack'
require 'rack/contrib/try_static'
require 'sprockets'
require 'sprockets-less'
require 'thin'

root_path = File.expand_path('..', File.dirname(__FILE__))

sprockets = Sprockets::Environment.new(root_path)
sprockets.append_path(File.expand_path('lib', root_path))
sprockets.append_path(File.expand_path('vendor', root_path))

app = Rack::Builder.new do
  use Rack::Lint
  use Rack::CommonLogger
  use Rack::TryStatic, {
    :urls => [''],
    :root => File.expand_path('examples', root_path),
    :index => 'index.html'
  }

  map '/assets' do
    run sprockets
  end
end

server = Thin::Server.new('0.0.0.0', 3000, app)
server.start
